const excludedTitle=/price\s*difference|compensation\s*link|item\s*personalization|deposit\s*(?:only|payment)|gift\s*card|sample\s*fee/i;
function dimensions(text){const m=String(text||'').replace(/\\/g,'').match(/(\d+(?:\.\d+)?)\s*["″]?\s*[x×*]\s*(\d+(?:\.\d+)?)(?:\s*["″]?\s*[x×*]\s*(\d+(?:\.\d+)?))?/i);if(!m)return null;const parts=m.slice(1).filter(Boolean).map(Number);return [...parts.slice(0,2).sort((a,b)=>a-b),...parts.slice(2)].join('x');}
// Giyim, ayakkabı, mutfak, ev ve duvar ürünlerinde tam 1,00 tutarı mağazanın yer tutucu fiyatıdır
// (gerçek fiyat tasarım ekranında hesaplanır). Etiket, bağcık, ambalaj gibi küçük ürünlerde 1,00 gerçek olabilir.
const placeholderGroups=new Set(['giyim','cocuk-bebek','ayakkabi','mutfak','ev','duvar']);
function reason(p){if(excludedTitle.test(p.title))return 'Ek hizmet/ödeme kaydı; ürün bedeli değil';if(/^\s*campaign\s*#?\s*\d+\s*$/i.test(p.title))return 'Satıcı kampanya kaydı; katalog ürünü değil';if(/^\s*test\b/i.test(p.title))return 'Mağazanın test kaydı; satıştaki ürün değil';if((p.sourceMinor??p.baseMinor)===100&&placeholderGroups.has(require('./pod-taxonomy.cjs').classify(p).group))return 'Tam 1,00 tutarı yer tutucu fiyat olabilir; gerçek ürün bedeli doğrulanmalı';if(!Number.isSafeInteger(p.baseMinor)||p.baseMinor<=0)return 'Geçersiz ürün bedeli';if(p.currency!=='USD')return 'Sıralama para birimi doğrulanmadı';if(p.sourceCurrency&&p.sourceCurrency!=='USD'&&(!(p.exchangeRate>0)||!Number.isSafeInteger(p.sourceMinor)||Math.round(p.sourceMinor*p.exchangeRate)!==p.baseMinor))return 'Kaynak para birimi veya kur dönüşümü uyuşmuyor';if(p.providerId==='printkk'&&(!p.priceVerified||!p.sourceVariantId||/customiz|custom\s*siz/i.test(p.sizes)))return 'Standart tek-adet varyant fiyatı doğrulanmadı';if(/Ex-Factory başlangıç/i.test(p.priceBasis))return 'Şartlı fabrika/adet fiyatı; standart tek ürün bedeli doğrulanmadı';if((p.sourceMinor??p.baseMinor)<100&&!p.priceVerified)return 'Düşük tutar: standart ürün varyantı ayrıca doğrulanmalı';if(p.providerId==='printify'&&p.sourceKind!=='api')return 'Elle alınmış eski fiyat; canlı kaynak doğrulaması bekliyor';return null;}
// Bir üreticinin kayıtlarının %5'inden fazlası (en az 10) tam 1,00 ise, o üreticinin bütün 1,00'lık kayıtları yer tutucudur.
function placeholderProviders(products){const all={},one={};for(const p of products){all[p.providerId]=(all[p.providerId]||0)+1;if((p.sourceMinor??p.baseMinor)===100)one[p.providerId]=(one[p.providerId]||0)+1;}return new Set(Object.keys(one).filter(id=>one[id]>=10&&one[id]/all[id]>0.05));}
function apply(products){const accepted=[],pending=[],bulkOne=placeholderProviders(products);for(const p of products){let error=reason(p);if(!error&&bulkOne.has(p.providerId)&&(p.sourceMinor??p.baseMinor)===100)error='Üreticinin çok sayıda kaydı tam 1,00; yer tutucu fiyat, gerçek ürün bedeli doğrulanmalı';if(!error&&p.providerId==='printkk'&&dimensions(p.title)&&dimensions(p.title)!==dimensions(p.sizes))error='Ürün adındaki ölçüyle fiyat varyantının ölçüsü uyuşmuyor';if(error)pending.push({...p,priceReviewReason:error});else accepted.push(p);}return {accepted,pending};}
module.exports={reason,apply};
